In [1]:
from transformers import pipeline

In [2]:
import transformers
print(transformers.__version__)

4.45.2


In [3]:
import librosa
import torch
from transformers import Wav2Vec2ForCTC, Wav2Vec2Tokenizer
import numpy as np


In [4]:
from IPython.display import display

In [5]:
tokenizer =  Wav2Vec2Tokenizer.from_pretrained("facebook/wav2vec2-base-960h")
model = Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-base-960h")

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'Wav2Vec2CTCTokenizer'. 
The class this function is called from is 'Wav2Vec2Tokenizer'.
C:\Users\shesh\anaconda3\envs\DeepLearning\lib\site-packages\transformers\models\wav2vec2\tokenization_wav2vec2.py:720: FutureWarning: The class `Wav2Vec2Tokenizer` is deprecated and will be removed in version 5 of Transformers. Please use `Wav2Vec2Processor` or `Wav2Vec2CTCTokenizer` instead.
  warnings.warn(
Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


# 1st File:

In [6]:
audio, sampling_rate = librosa.load("audio.wav", sr=16000)

In [7]:
audio,sampling_rate

(array([ 4.5505419e-02,  8.1750043e-02,  7.5508349e-02, ...,
        -6.5084270e-05, -2.1607296e-04, -3.6561210e-04], dtype=float32),
 16000)

In [8]:
from IPython.display import Audio

# Create an audio object and play it
audio = Audio("audio1.wav", autoplay=True)
display(audio)


In [9]:
import librosa
from transformers import Wav2Vec2Tokenizer

# Load the tokenizer
tokenizer = Wav2Vec2Tokenizer.from_pretrained("facebook/wav2vec2-base-960h")

# Load the audio file (make sure the path is correct)
audio_path = "audio1.wav"
audio, sample_rate = librosa.load(audio_path, sr=16000)  # Load with the correct sample rate

# Tokenize the audio input
input_values = tokenizer(audio, return_tensors='pt').input_values

# Display the tokenized input values
print(input_values)


The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'Wav2Vec2CTCTokenizer'. 
The class this function is called from is 'Wav2Vec2Tokenizer'.


tensor([[0.0008, 0.0048, 0.0065,  ..., 0.0371, 0.0401, 0.0597]])


C:\Users\shesh\anaconda3\envs\DeepLearning\lib\site-packages\transformers\models\wav2vec2\tokenization_wav2vec2.py:720: FutureWarning: The class `Wav2Vec2Tokenizer` is deprecated and will be removed in version 5 of Transformers. Please use `Wav2Vec2Processor` or `Wav2Vec2CTCTokenizer` instead.
  warnings.warn(


In [10]:
logits = model(input_values).logits
logits

tensor([[[ 15.0072, -27.8702, -27.5920,  ...,  -6.5019,  -7.8916,  -7.6024],
         [ 15.1128, -27.8972, -27.6098,  ...,  -6.4304,  -7.8843,  -7.5696],
         [ 15.1433, -27.7539, -27.4539,  ...,  -6.3350,  -7.8039,  -7.5202],
         ...,
         [ 15.0655, -28.1545, -27.8974,  ...,  -6.5123,  -8.1057,  -7.6391],
         [ 14.9486, -27.9497, -27.6921,  ...,  -6.4949,  -8.4349,  -7.5192],
         [ 14.5755, -27.7046, -27.4301,  ...,  -6.4725,  -8.4781,  -7.5957]]],
       grad_fn=<ViewBackward0>)

In [11]:
predicted_ids = torch.argmax(logits, dim= -1)

In [12]:
transcriptions = tokenizer.decode(predicted_ids[0]) 

In [13]:
transcriptions

'I HAVE BEEN IN MY DIST THERE IT TURDINS ME'

# 2nd file:

In [14]:
from IPython.display import Audio

# Create an audio object and play it
audio = Audio("dont_forget.wav", autoplay=True)
display(audio)

In [15]:
import librosa
from transformers import Wav2Vec2Tokenizer

# Load the tokenizer
tokenizer = Wav2Vec2Tokenizer.from_pretrained("facebook/wav2vec2-base-960h")

# Load the audio file (make sure the path is correct)
audio_path = "dont_forget.wav"
audio, sample_rate = librosa.load(audio_path, sr=16000)  # Load with the correct sample rate

# Tokenize the audio input
input_values = tokenizer(audio, return_tensors='pt').input_values

# Display the tokenized input values
print(input_values)

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'Wav2Vec2CTCTokenizer'. 
The class this function is called from is 'Wav2Vec2Tokenizer'.


tensor([[-0.0003, -0.0003, -0.0003,  ...,  0.0006, -0.0003, -0.0003]])


In [16]:
logits = model(input_values).logits
logits

tensor([[[ 13.3411, -27.6910, -27.4074,  ...,  -7.1431,  -7.6148,  -8.2868],
         [ 13.4637, -27.7012, -27.4091,  ...,  -7.2955,  -7.8028,  -8.3078],
         [ 13.3275, -27.5689, -27.2858,  ...,  -7.2252,  -7.6768,  -8.3432],
         ...,
         [ 13.2757, -26.9496, -26.6530,  ...,  -5.9063,  -7.3677,  -7.6714],
         [ 13.4129, -27.4782, -27.2001,  ...,  -7.1501,  -7.8669,  -8.0720],
         [ 13.3292, -27.3755, -27.0866,  ...,  -7.0040,  -7.8861,  -7.9307]]],
       grad_fn=<ViewBackward0>)

In [17]:
predicted_ids = torch.argmax(logits, dim= -1)

In [18]:
transcriptions = tokenizer.decode(predicted_ids[0]) 

In [19]:
transcriptions

"DON'T FORGET A JACKET"

# 3rd File:

In [20]:
from IPython.display import Audio

# Create an audio object and play it
audio = Audio("11Oclock.wav", autoplay=True)
display(audio)


In [21]:
import librosa
from transformers import Wav2Vec2Tokenizer

# Load the tokenizer
tokenizer = Wav2Vec2Tokenizer.from_pretrained("facebook/wav2vec2-base-960h")

# Load the audio file (make sure the path is correct)
audio_path = "11Oclock.wav"
audio, sample_rate = librosa.load(audio_path, sr=16000)  # Load with the correct sample rate

# Tokenize the audio input
input_values = tokenizer(audio, return_tensors='pt').input_values

# Display the tokenized input values
print(input_values)

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'Wav2Vec2CTCTokenizer'. 
The class this function is called from is 'Wav2Vec2Tokenizer'.


tensor([[-0.0007, -0.0091,  0.0040,  ..., -0.0011,  0.0010, -0.0002]])


In [22]:
logits = model(input_values).logits
logits

tensor([[[ 13.1418, -26.1992, -25.9298,  ...,  -6.0040,  -7.4830,  -6.7419],
         [ 13.3433, -26.7327, -26.4619,  ...,  -6.3075,  -7.7448,  -6.9541],
         [ 12.9827, -25.3902, -25.1217,  ...,  -5.4603,  -7.0517,  -6.3241],
         ...,
         [ 13.4134, -27.1296, -26.8706,  ...,  -6.8734,  -7.9754,  -7.1132],
         [ 13.2423, -26.9779, -26.7236,  ...,  -6.8797,  -7.9631,  -7.1585],
         [ 13.1660, -26.9106, -26.6516,  ...,  -6.8994,  -8.0195,  -7.1608]]],
       grad_fn=<ViewBackward0>)

In [23]:
predicted_ids = torch.argmax(logits, dim= -1)

In [24]:
transcriptions = tokenizer.decode(predicted_ids[0]) 

In [25]:
transcriptions

"IT'S ELEVEN O'CLOCK"